name: test_ip

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Load Cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set Timezone
        run: sudo timedatectl set-timezone 'Asia/Tehran'
      - name: Install Dependencies
        run: |
          pip install -r ./utils/requirements.txt
      - name: Run Ip Test
        run: |
          sudo sh ./utils/speedtest/ip_test.sh
